### ISSUE TITLE
Uitbreiding van README.md

### ISSUE THREAD

**Issue by ketelaar** [ketelaar/pws_priemen#7]
Deze kunnen we misschien uitbreiden om wat basisinformatie over ons project te geven. Zou jij dit kunnen doen @PascalleGeerts ?

**Comment by PascalleGeerts** [comment]
[Algemene informatie over ons PWS.docx](https://github.com/ketelaar/pws_priemen/files/594970/Algemene.informatie.over.ons.PWS.docx)
Is dit zoals je het bedoelde? @ketelaar

**Comment by ketelaar** [comment]
Ja, dat ziet er prima uit. @PascalleGeerts  Ik heb het word-bestand voor je omgezet naar Markdown (formaat die het README bestand gebruikt). Kijk maar of alles goed is. Als alles er goed uit ziet kan je README.md in de README-update branch updaten met de Markdown code die ik je gegeven heb. Als je vragen hebt over hoe je dat moet doen, dan kan je die hier stellen

https://gist.github.com/ketelaar/2b45a90d752092eb56503f9bcc25b9b9
